export const ENDPOINTS = {
    AUTH: {
        LOGIN: '/auth/login',
        LOGOUT: '/auth/logout',
        REFRESH: '/auth/refresh',
        ME: '/auth/me',
        FORGOT_PASSWORD: '/auth/forgot-password',
        RESET_PASSWORD: '/auth/reset-password',
        ACTIVATE_ACCOUNT: '/auth/activate-account',
        CHANGE_PASSWORD: '/auth/change-password',
    },
    EMPLOYEES: {
        BASE: '/employees',
        DETAIL: (id: string) => `/employees/${id}`,
        ACTIVATE: (id: string) => `/employees/${id}/activate`,
        DEACTIVATE: (id: string) => `/employees/${id}/deactivate`,
        UPLOAD_PHOTO: (id: string) => `/employees/${id}/photo`,
        GET_PHOTO: (id: string) => `/employees/${id}/photo`,
        SEARCH: '/employees/search',
    },
    TASKS: {
        BASE: '/tasks',
        DETAIL: (id: string) => `/tasks/${id}`,
        STATUS: (id: string) => `/tasks/${id}/status`,
        COMMENTS: (id: string) => `/tasks/${id}/comments`,
        ATTACHMENTS: (id: string) => `/tasks/${id}/attachments`,
        HISTORY: (id: string) => `/tasks/${id}/history`,
        MY_TASKS: '/tasks/my-tasks',
        OVERDUE: '/tasks/overdue',
        SEARCH: '/tasks/search',
    },
    ANALYTICS: {
        DASHBOARD_ADMIN: '/analytics/dashboard/admin',
        DASHBOARD_EMPLOYEE: '/analytics/dashboard/employee',
        TASK_DISTRIBUTION: '/analytics/tasks/distribution',
        TASK_BY_PRIORITY: '/analytics/tasks/by-priority',
        COMPLETION_TREND: '/analytics/tasks/completion-trend',
        EMPLOYEE_PERFORMANCE: '/analytics/employees/performance',
        REPORT_EXPORT: '/analytics/reports/export',
        REPORT_DOWNLOAD: (id: string) => `/analytics/reports/${id}/download`,
    },
};
